CREATE TABLE IF NOT EXISTS books (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  year INT NOT NULL,
  genre VARCHAR(255) NOT NULL,
  image VARCHAR(500) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS migrations (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  schema_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);